import { z } from "zod";

import {
    defineNotificationType,
    educationLevelOptions,
    raceColorOptions,
    sexOptions,
    yesNoUnknownOptions,
    type NotificationSectionDefinition,
} from "@/features/notifications/definitions/shared"

const optionalTextSchema = z.string().min(1, "Campo obrigatório");

// -----------------------------------------------------------------------------
// 1. DADOS GERAIS (Campos 1 a 7)
// -----------------------------------------------------------------------------
const generalSection = {
    id: "general",
    title: "Dados Gerais",
    description: "Informações básicas da notificação e unidade de saúde. [cite: 6]",
    columns: 3,
    fields: [
        {
            name: "tp_notification",
            label: "Tipo de Notificação",
            kind: "select",
            schema: z.string(),
            defaultValue: "2",
            options: [{ label: "2 - Individual", value: "2" }],
        },
        {
            name: "dt_notification",
            label: "Data da Notificação",
            kind: "date",
            schema: z.string().min(1, "Data obrigatória"),
            defaultValue: "",
        },
        {
            name: "uf_notification",
            label: "UF de Notificação",
            kind: "text",
            schema: z.string().min(2, "UF obrigatória"),
            defaultValue: "",
        },
        {
            name: "city_notification",
            label: "Município de Notificação",
            kind: "text",
            schema: z.string().min(1, "Município obrigatório"),
            defaultValue: "",
        },
        {
            name: "health_unit_name",
            label: "Unidade de Saúde (ou outra fonte notificadora)",
            kind: "text",
            schema: z.string().min(1, "Unidade obrigatória"),
            defaultValue: "",
        },
        {
            name: "dt_first_symptoms",
            label: "Data dos Primeiros Sintomas",
            kind: "date",
            schema: z.string().min(1, "Data obrigatória"),
            defaultValue: "",
        },
    ],
} satisfies NotificationSectionDefinition;

// -----------------------------------------------------------------------------
// 2. DADOS DO PACIENTE (Campos 8 a 16 e 31)
// -----------------------------------------------------------------------------
const patientSection = {
    id: "patient",
    title: "Dados do Paciente",
    description: "Identificação e dados sociodemográficos da Notificação Individual. [cite: 5]",
    columns: 3,
    fields: [
        {
            name: "patient_name",
            label: "Nome do Paciente",
            kind: "text",
            schema: z.string().min(3, "Nome obrigatório"),
            defaultValue: "",
        },
        {
            name: "patient_birth_date",
            label: "Data de Nascimento",
            kind: "date",
            schema: optionalTextSchema,
            defaultValue: "",
        },
        {
            name: "patient_age",
            label: "Idade (com código da unidade)",
            kind: "text",
            schema: optionalTextSchema,
            defaultValue: "",
        },
        {
            name: "sex",
            label: "Sexo",
            kind: "select",
            schema: z.string().min(1, "Sexo obrigatório"),
            defaultValue: "",
            options: sexOptions,
        },
        {
            name: "pregnant",
            label: "Gestante",
            kind: "select",
            schema: optionalTextSchema,
            defaultValue: "6",
            options: [
                { label: "1 - 1º Trimestre", value: "1" },
                { label: "2 - 2º Trimestre", value: "2" },
                { label: "3 - 3º Trimestre", value: "3" },
                { label: "4 - Idade gestacional ignorada", value: "4" },
                { label: "5 - Não", value: "5" },
                { label: "6 - Não se aplica", value: "6" },
                { label: "9 - Ignorado", value: "9" },
            ],
        },
        {
            name: "race_color",
            label: "Raça/Cor",
            kind: "select",
            schema: optionalTextSchema,
            defaultValue: "9",
            options: raceColorOptions,
        },
        {
            name: "education_level",
            label: "Escolaridade",
            kind: "select",
            schema: optionalTextSchema,
            defaultValue: "9",
            options: educationLevelOptions,
        },
        {
            name: "sus_card_number",
            label: "Número do Cartão SUS",
            kind: "text",
            schema: optionalTextSchema,
            defaultValue: "",
        },
        {
            name: "mother_name",
            label: "Nome da mãe",
            kind: "text",
            schema: optionalTextSchema,
            defaultValue: "",
        },
        {
            name: "occupation",
            label: "Ocupação",
            kind: "text",
            schema: optionalTextSchema,
            defaultValue: "",
        },
    ],
} satisfies NotificationSectionDefinition;

// -----------------------------------------------------------------------------
// 3. DADOS DE RESIDÊNCIA (Campos 17 a 30)
// -----------------------------------------------------------------------------
const residenceSection = {
    id: "residence",
    title: "Dados de Residência",
    description: "Informações de endereço de residência do paciente. [cite: 4]",
    columns: 3,
    fields: [
        {
            name: "residence_state",
            label: "UF",
            kind: "text",
            schema: z.string().min(2, "UF obrigatória"),
            defaultValue: "",
        },
        {
            name: "residence_city",
            label: "Município de Residência",
            kind: "text",
            schema: z.string().min(1, "Município obrigatório"),
            defaultValue: "",
        },
        {
            name: "residence_district",
            label: "Distrito",
            kind: "text",
            schema: optionalTextSchema,
            defaultValue: "",
        },
        {
            name: "residence_neighborhood",
            label: "Bairro",
            kind: "text",
            schema: optionalTextSchema,
            defaultValue: "",
        },
        {
            name: "residence_street",
            label: "Logradouro (rua, avenida,...)",
            kind: "text",
            schema: optionalTextSchema,
            defaultValue: "",
        },
        {
            name: "residence_number",
            label: "Número",
            kind: "text",
            schema: optionalTextSchema,
            defaultValue: "",
        },
        {
            name: "residence_complement",
            label: "Complemento (apto., casa, ...)",
            kind: "text",
            schema: optionalTextSchema,
            defaultValue: "",
        },
        {
            name: "residence_geo1",
            label: "Geo campo 1",
            kind: "text",
            schema: optionalTextSchema,
            defaultValue: "",
        },
        {
            name: "residence_geo2",
            label: "Geo campo 2",
            kind: "text",
            schema: optionalTextSchema,
            defaultValue: "",
        },
        {
            name: "residence_reference",
            label: "Ponto de Referência",
            kind: "text",
            schema: optionalTextSchema,
            defaultValue: "",
        },
        {
            name: "residence_cep",
            label: "CEP",
            kind: "text",
            schema: optionalTextSchema,
            defaultValue: "",
        },
        {
            name: "residence_phone",
            label: "(DDD) Telefone",
            kind: "text",
            schema: optionalTextSchema,
            defaultValue: "",
        },
        {
            name: "residence_zone",
            label: "Zona",
            kind: "select",
            schema: optionalTextSchema,
            defaultValue: "9",
            options: [
                { label: "1 - Urbana", value: "1" },
                { label: "2 - Rural", value: "2" },
                { label: "3 - Periurbana", value: "3" },
                { label: "9 - Ignorado", value: "9" },
            ],
        },
        {
            name: "residence_country",
            label: "País (se residente fora do Brasil)",
            kind: "text",
            schema: optionalTextSchema,
            defaultValue: "",
        },
    ],
} satisfies NotificationSectionDefinition;

// -----------------------------------------------------------------------------
// Dados Complementares do Caso
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// 4. Dados da Pessoa Atendida (Campo 33, 35 a 39)
// -----------------------------------------------------------------------------

const patientDataSection = {
    id: "patient_and_occurrence",
    title: "Dados da Pessoa Atendida e Dados da Ocorrência",
    description: "Informações socioambientais e dados geográficos/circunstanciais da ocorrência",
    columns: 3,
    fields: [
        {
            name: "social_name",
            label: "Nome Social",
            kind: "text",
            schema: z.string().optional(),
            defaultValue: "",
        },
        {
            name: "marital_status",
            label: "Situação conjugal / Estado civil",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: [
                { value: "1", label: "1 - Solteiro" },
                { value: "2", label: "2 - Casado/união consensual" },
                { value: "3", label: "3 - Viúvo" },
                { value: "4", label: "4 - Separado" },
                { value: "8", label: "8 - Não se aplica" },
                { value: "9", label: "9 - Ignorado" },
            ],
        },
        {
            name: "sexual_orientation",
            label: "Orientação Sexual",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: [
                { value: "1", label: "1 - Heterossexual" },
                { value: "2", label: "2 - Homossexual (gay/lésbica)" },
                { value: "3", label: "3 - Bissexual" },
                { value: "8", label: "8 - Não se aplica" },
                { value: "9", label: "9 - Ignorado" },
            ],
        },
        {
            name: "gender_identity",
            label: "Identidade de gênero",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: [
                { value: "1", label: "1 - Travesti" },
                { value: "2", label: "2 - Mulher Transexual" },
                { value: "3", label: "3 - Homem Transexual" },
                { value: "8", label: "8 - Não se aplica" },
                { value: "9", label: "9 - Ignorado" },
            ],
        },
        {
            name: "has_disability_or_disorder",
            label: "Possui algum tipo de deficiência/ transtorno?",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "disability_physical",
            label: "Deficiência Física",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "disability_intellectual",
            label: "Deficiência Intelectual",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "disability_visual",
            label: "Deficiência visual",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "disability_auditory",
            label: "Deficiência auditiva",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "disorder_mental",
            label: "Transtorno mental",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "disorder_behavioral",
            label: "Transtorno de comportamento",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "disability_other",
            label: "Outras (Deficiência/Transtorno)",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "disability_other_description",
            label: "Especificação de Outras Deficiências/Transtornos",
            kind: "text",
            schema: z.string().optional(),
            defaultValue: "",
        },
    ],
} satisfies NotificationSectionDefinition;    

// -----------------------------------------------------------------------------
// 5. Dados da Ocorrência (Campo 40 a 54)
// -----------------------------------------------------------------------------
const occurrenceSection = {
    id: "occurrence",
    title: "Dados da Ocorrência",
    description: " Circunstanciais da ocorrência",
    columns: 3,
    fields: [
        {
            name: "occurrence_uf",
            label: "UF de ocorrência",
            kind: "text",
            schema:  z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
        },
        {
            name: "occurrence_municipality",
            label: "Município de ocorrência",
            kind: "text",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
        },
        {
            name: "occurrence_district",
            label: "Distrito",
            kind: "text",
            schema:  z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
        },
        {
            name: "occurrence_neighborhood",
            label: "Bairro",
            kind: "text",
            schema:  z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
        },
        {
            name: "occurrence_address",
            label: "Logradouro (rua, avenida,...)",
            kind: "text",
            schema:  z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
        },
        {
            name: "occurrence_number",
            label: "Número",
            kind: "text",
            schema: z.string().optional(),
            defaultValue: "",
        },
        {
            name: "occurrence_complement",
            label: "Complemento (apto., casa, ...)",
            kind: "text",
            schema: z.string().optional(),
            defaultValue: "",
        },
        {
            name: "occurrence_geo_field_3",
            label: "Geo campo 3",
            kind: "text",
            schema: z.string().optional(),
            defaultValue: "",
        },
        {
            name: "occurrence_geo_field_4",
            label: "Geo campo 4",
            kind: "text",
            schema: z.string().optional(),
            defaultValue: "",
        },
        {
            name: "occurrence_reference_point",
            label: "Ponto de Referência",
            kind: "text",
            schema: z.string().optional(),
            defaultValue: "",
        },
        {
            name: "occurrence_zone",
            label: "Zona",
            kind: "select",
            schema:  z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: [
                { value: "1", label: "1 - Urbana" },
                { value: "2", label: "2 - Rural" },
                { value: "3", label: "3 - Periurbana" },
                { value: "9", label: "9 - Ignorado" },
            ],
        },
        {
            name: "occurrence_time",
            label: "Hora da ocorrência (00:00 - 23:59)",
            kind: "text",
            schema:  z.string().min(1, "Campo obrigatório"), 
            defaultValue: "",
        },
        {
            name: "occurrence_place",
            label: "Local de ocorrência",
            kind: "select",
            schema:  z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: [
                { value: "01", label: "01 - Residência" },
                { value: "02", label: "02 - Habitação coletiva" },
                { value: "03", label: "03 - Escola" },
                { value: "04", label: "04 - Local de prática esportiva" },
                { value: "05", label: "05 - Bar ou similar" },
                { value: "06", label: "06 - Via pública" },
                { value: "07", label: "07 - Comércio/serviços" },
                { value: "08", label: "08 - Indústrias/construção" },
                { value: "09", label: "09 - Outro" },
                { value: "99", label: "99 - Ignorado" },
            ],
        },
        {
            name: "occurrence_place_other_description",
            label: "Especificação se 09 (Outro Local)",
            kind: "text",
            schema: z.string().optional(),
            defaultValue: "",
        },
        {
            name: "occurred_other_times",
            label: "Ocorreu outras vezes?",
            kind: "select",
            schema:  z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "was_self_inflicted",
            label: "A lesão foi autoprovocada?",
            kind: "select",
            schema: z.string().optional(),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
    ],
} satisfies NotificationSectionDefinition;

// -----------------------------------------------------------------------------
// 6. Violência (Campo 55 a 57)
// -----------------------------------------------------------------------------

const violenceSection = {
    id: "violence_data",
    title: "Violência",
    description: "Informações sobre a motivação, tipos de violência, meios de agressão e procedimentos realizados",
    columns: 3,
    fields: [
        {
            name: "violence_motivation",
            label: "Essa violência foi motivada por:",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: [
                { value: "01", label: "01 - Sexismo" },
                { value: "02", label: "02 - Homofobia/Lesbofobia/Bifobia/Transfobia" },
                { value: "03", label: "03 - Racismo" },
                { value: "04", label: "04 - Intolerância religiosa" },
                { value: "05", label: "05 - Xenofobia" },
                { value: "06", label: "06 - Conflito geracional" },
                { value: "07", label: "07 - Situação de rua" },
                { value: "08", label: "08 - Deficiência" },
                { value: "09", label: "09 - Outros" },
                { value: "88", label: "88 - Não se aplica" },
                { value: "99", label: "99 - Ignorado" },
            ],
        },
        {
            name: "violence_motivation_other_desc",
            label: "Especificação se 09 (Outra Motivação)",
            kind: "text",
            schema: z.string().optional(),
            defaultValue: "",
        },
        {
            name: "violence_type_physical",
            label: "Tipo de violência: Física",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "violence_type_psychological",
            label: "Tipo de violência: Psicológica/Moral",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "violence_type_torture",
            label: "Tipo de violência: Tortura",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "violence_type_sexual",
            label: "Tipo de violência: Sexual",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "violence_type_human_trafficking",
            label: "Tipo de violência: Tráfico de seres humanos",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "violence_type_financial",
            label: "Tipo de violência: Financeira/Econômica",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "violence_type_neglect",
            label: "Tipo de violência: Negligência/Abandono",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "violence_type_child_labor",
            label: "Tipo de violência: Trabalho infantil",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "violence_type_legal_intervention",
            label: "Tipo de violência: Intervenção legal",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "violence_type_other",
            label: "Tipo de violência: Outros",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "violence_type_other_desc",
            label: "Especificação se Outro Tipo de Violência",
            kind: "text",
            schema: z.string().optional(),
            defaultValue: "",
        },
        // Meio de agressão
        {
            name: "aggression_means_body_force",
            label: "Meio de agressão: Força corporal/espancamento",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "aggression_means_hanging",
            label: "Meio de agressão: Enforcamento",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "aggression_means_blunt_object",
            label: "Meio de agressão: Obj. contundente",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "aggression_means_sharp_object",
            label: "Meio de agressão: Obj. pérfuro-cortante",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "aggression_means_substance",
            label: "Meio de agressão: Substância/Obj. quente",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "aggression_means_poisoning",
            label: "Meio de agressão: Envenenamento, Intoxicação",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "aggression_means_firearm",
            label: "Meio de agressão: Arma de fogo",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "aggression_means_threat",
            label: "Meio de agressão: Ameaça",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "aggression_means_other",
            label: "Meio de agressão: Outro",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "aggression_means_other_desc",
            label: "Especificação se Outro Meio de Agressão",
            kind: "text",
            schema: z.string().optional(),
            defaultValue: "",
        },
    ],
} satisfies NotificationSectionDefinition;

// -----------------------------------------------------------------------------
// 7. Violência Sexual (Campo 58 a 59)
// -----------------------------------------------------------------------------

const violenceSexualSection = {
    id: "violence_sexual_data",
    title: "Violência Sexual",
    description: "Informações sobre tipos de violência",
    columns: 3,
    fields: [
        {
            name: "sexual_violence_harassment",
            label: "Violência sexual: Assédio sexual",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "sexual_violence_rape",
            label: "Violência sexual: Estupro",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "sexual_violence_pornography",
            label: "Violência sexual: Pornografia infantil",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "sexual_violence_exploitation",
            label: "Violência sexual: Exploração sexual",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "sexual_violence_other",
            label: "Violência sexual: Outros",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "sexual_violence_other_desc",
            label: "Especificação se Outro Tipo de Violência Sexual",
            kind: "text",
            schema: z.string().optional(),
            defaultValue: "",
        },
        {
            name: "procedure_std_prophylaxis",
            label: "Procedimento: Profilaxia DST",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "procedure_hiv_prophylaxis",
            label: "Procedimento: Profilaxia HIV",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "procedure_hepatitis_b_prophylaxis",
            label: "Procedimento: Profilaxia Hepatite B",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "procedure_blood_collection",
            label: "Procedimento: Coleta de sangue",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "procedure_semen_collection",
            label: "Procedimento: Coleta de sêmen",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "procedure_vaginal_secretion_collection",
            label: "Procedimento: Coleta de secreção vaginal",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "procedure_emergency_contraception",
            label: "Procedimento: Contracepção de emergência",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "procedure_lawful_abortion",
            label: "Procedimento: Aborto previsto em lei",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
    ],
} satisfies NotificationSectionDefinition;

// -----------------------------------------------------------------------------
// 8. Dados do provável autor da violência (Campo 60 a 64)
// -----------------------------------------------------------------------------

const perpetratorSection = {
    id: "perpetrator",
    title: "Dados do Autor",
    description: "Informações sobre o provável autor da violência",
    columns: 3,
    fields: [
        {
            name: "perpetrators_number",
            label: "Número de envolvidos",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: [
                { value: "1", label: "1 - Um" },
                { value: "2", label: "2 - Dois ou mais" },
                { value: "9", label: "9 - Ignorado" },
            ],
        },
        {
            name: "relationship_father",
            label: "Vínculo: Pai",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "relationship_mother",
            label: "Vínculo: Mãe",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "relationship_stepfather",
            label: "Vínculo: Padrasto",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "relationship_stepmother",
            label: "Vínculo: Madrasta",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "relationship_spouse",
            label: "Vínculo: Cônjuge",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "relationship_ex_spouse",
            label: "Vínculo: Ex-Cônjuge",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "relationship_partner",
            label: "Vínculo: Namorado(a)",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "relationship_ex_partner",
            label: "Vínculo: Ex-Namorado(a)",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "relationship_child",
            label: "Vínculo: Filho(a)",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "relationship_sibling",
            label: "Vínculo: Irmão(ã)",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "relationship_friend",
            label: "Vínculo: Amigos/conhecidos",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "relationship_stranger",
            label: "Vínculo: Desconhecido(a)",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "relationship_caregiver",
            label: "Vínculo: Cuidador(a)",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "relationship_boss",
            label: "Vínculo: Patrão/chefe",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "relationship_institutional",
            label: "Vínculo: Pessoa com relação institucional",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "relationship_law_enforcement",
            label: "Vínculo: Policial/agente da lei",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "relationship_self",
            label: "Vínculo: Própria pessoa",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "relationship_other",
            label: "Vínculo: Outros",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "relationship_other_desc",
            label: "Especificação se Outro Vínculo",
            kind: "text",
            schema: z.string().optional(),
            defaultValue: "",
        },
        {
            name: "perpetrator_sex",
            label: "Sexo do provável autor da violência",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: [
                { value: "1", label: "1 - Masculino" },
                { value: "2", label: "2 - Feminino" },
                { value: "3", label: "3 - Ambos os sexos" },
                { value: "9", label: "9 - Ignorado" },
            ],
        },
        {
            name: "perpetrator_alcohol_suspicion",
            label: "Suspeita de uso de álcool",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "perpetrator_life_cycle",
            label: "Ciclo de vida do provável autor da violência",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: [
                { value: "1", label: "1 - Criança (0 a 9 anos)" },
                { value: "2", label: "2 - Adolescente (10 a 19 anos)" },
                { value: "3", label: "3 - Jovem (20 a 24 anos)" },
                { value: "4", label: "4 - Pessoa adulta (25 a 59 anos)" },
                { value: "5", label: "5 - Pessoa idosa (60 anos ou mais)" },
                { value: "9", label: "9 - Ignorado" },
            ],
        },
    ],
} satisfies NotificationSectionDefinition;

// -----------------------------------------------------------------------------
// 9. Encaminhamento (Campo 65)
// -----------------------------------------------------------------------------

const referralNetworkSection = {
    id: "referral_network",
    title: "Encaminhamento",
    description: "Rede de encaminhamento",
    columns: 3,
    fields: [
        {
            name: "referral_health_network",
            label: "Encaminhamento: Rede da Saúde",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "referral_social_assistance",
            label: "Encaminhamento: Rede da Assistência Social (CRAS, CREAS...)",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "referral_education_network",
            label: "Encaminhamento: Rede da Educação (Creche, escola...)",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "referral_women_service",
            label: "Encaminhamento: Rede de Atendimento à Mulher (Centro Especializado de Atendimento à Mulher, Casa da Mulher Brasileira, outras)",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "referral_tutoriary_council",
            label: "Encaminhamento: Conselho Tutelar",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "referral_elderly_council",
            label: "Encaminhamento: Conselho do Idoso",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "referral_elderly_police",
            label: "Encaminhamento: Delegacia de Atendimento ao Idoso",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "referral_human_rights",
            label: "Encaminhamento: Centro de Referência dos Direitos Humanos",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "referral_public_ministry",
            label: "Encaminhamento: Ministério Público",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "referral_child_police",
            label: "Encaminhamento: Delegacia Especializada de Proteção à Criança e Adolescente",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "referral_women_police",
            label: "Encaminhamento: Delegacia de Atendimento à Mulher",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "referral_other_police",
            label: "Encaminhamento: Outras delegacias",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "referral_child_justice",
            label: "Encaminhamento: Justiça da Infância e da Juventude",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "referral_public_defender",
            label: "Encaminhamento: Defensoria Pública",
            kind: "select",
            schema: z.string().min(1, "Campo obrigatório"),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
    ],
} satisfies NotificationSectionDefinition;

// -----------------------------------------------------------------------------
// 10. Conclusão (Campo 66 a 69)
// -----------------------------------------------------------------------------

const conclusionSection = {
    id: "conclusion",
    title: "Conclusão",
    description: "Encerramento do caso",
    columns: 3,
    fields: [
        {
            name: "work_related_violence",
            label: "Violência Relacionada ao Trabalho",
            kind: "select",
            schema: z.string().optional(),
            defaultValue: "",
            options: yesNoUnknownOptions,
        },
        {
            name: "cat_emitted",
            label: "Se sim, foi emitida a Comunicação de Acidente do Trabalho (CAT)",
            kind: "select",
            schema: z.string().optional(),
            defaultValue: "",
            options: [
                { value: "1", label: "1 - Sim" },
                { value: "2", label: "2 - Não" },
                { value: "8", label: "8 - Não se aplica" },
                { value: "9", label: "9 - Ignorado" },
            ],
        },
        {
            name: "injury_circumstance_cid10",
            label: "Circunstância da lesão (CID 10 - Cap XX)",
            kind: "text",
            schema: z.string().max(4).optional(),
            defaultValue: "",
        },
        {
            name: "closure_date",
            label: "Data de encerramento",
            kind: "date",
            schema: z.string().optional(),
            defaultValue: "",
        },

        // --- BLOCO: INFORMAÇÕES COMPLEMENTARES E OBSERVAÇÕES ---
        {
            name: "companion_name",
            label: "Nome do acompanhante",
            kind: "text",
            schema: z.string().optional(),
            defaultValue: "",
        },
        {
            name: "companion_relationship",
            label: "Vínculo/grau de parentesco (Acompanhante)",
            kind: "text",
            schema: z.string().optional(),
            defaultValue: "",
        },
        {
            name: "companion_phone",
            label: "(DDD) Telefone do acompanhante",
            kind: "text",
            schema: z.string().optional(),
            defaultValue: "",
        },
        {
            name: "additional_observations",
            label: "Observações Adicionais",
            kind: "text", // Se o seu componente aceitar, "textarea" seria o ideal aqui.
            schema: z.string().optional(),
            defaultValue: "",
        },
    ],
} satisfies NotificationSectionDefinition;

// -----------------------------------------------------------------------------
// Informações complementares e observações
// -----------------------------------------------------------------------------

const complementarSection = {
    id: "complementary_info",
    title: "Informações complementares e observações",
    description: "Informações complementares e observações",
    columns: 3,
    fields: [
        {
            name: "companion_name",
            label: "Nome do acompanhante",
            kind: "text",
            schema: z.string().optional(),
            defaultValue: "",
        },
        {
            name: "companion_relationship",
            label: "Vínculo/grau de parentesco (Acompanhante)",
            kind: "text",
            schema: z.string().optional(),
            defaultValue: "",
        },
        {
            name: "companion_phone",
            label: "(DDD) Telefone do acompanhante",
            kind: "text",
            schema: z.string().optional(),
            defaultValue: "",
        },
        {
            name: "additional_observations",
            label: "Observações Adicionais",
            kind: "text",
            schema: z.string().optional(),
            defaultValue: "",
        },
    ],
} satisfies NotificationSectionDefinition;


const sections = [
    generalSection,
    patientSection,
    residenceSection,
    occurrenceSection,
    patientDataSection,
    violenceSection,
    violenceSexualSection,
    perpetratorSection,
    referralNetworkSection,
    conclusionSection,
    complementarSection,
] as const satisfies readonly NotificationSectionDefinition[];

export const diphtheriaNotificationDefinition = defineNotificationType({
    id: 10, //alterar id
    slug: "interpersonal_self_violence",
    label: "VIOLÊNCIA INTERPESSOAL/AUTOPROVOCADA",
    description: "Caso suspeito ou confirmado de violência doméstica/intrafamiliar, sexual, autoprovocada, tráfico de pessoas, trabalho escravo, trabalho infantil, tortura, intervenção legal e violências homofóbicas contra mulheres e homens em todas as idades. No caso de violência extrafamiliar/comunitária, somente serão objetos de notificação as violências contra crianças, adolescentes, mulheres, pessoas idosas, pessoa com deficiência, indígenas e população LGBT.",
    sections,
});
